// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drug.proto

package drug

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDrugResponse_DrugStatus int32

const (
	GetDrugResponse_NORMAL        GetDrugResponse_DrugStatus = 0
	GetDrugResponse_DRUG_NO_FOUND GetDrugResponse_DrugStatus = 1
)

var GetDrugResponse_DrugStatus_name = map[int32]string{
	0: "NORMAL",
	1: "DRUG_NO_FOUND",
}

var GetDrugResponse_DrugStatus_value = map[string]int32{
	"NORMAL":        0,
	"DRUG_NO_FOUND": 1,
}

func (x GetDrugResponse_DrugStatus) String() string {
	return proto.EnumName(GetDrugResponse_DrugStatus_name, int32(x))
}

func (GetDrugResponse_DrugStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_909770b946af92c6, []int{3, 0}
}

type SearchDrugRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CurrentPage          int32    `protobuf:"varint,2,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchDrugRequest) Reset()         { *m = SearchDrugRequest{} }
func (m *SearchDrugRequest) String() string { return proto.CompactTextString(m) }
func (*SearchDrugRequest) ProtoMessage()    {}
func (*SearchDrugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_909770b946af92c6, []int{0}
}

func (m *SearchDrugRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchDrugRequest.Unmarshal(m, b)
}
func (m *SearchDrugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchDrugRequest.Marshal(b, m, deterministic)
}
func (m *SearchDrugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchDrugRequest.Merge(m, src)
}
func (m *SearchDrugRequest) XXX_Size() int {
	return xxx_messageInfo_SearchDrugRequest.Size(m)
}
func (m *SearchDrugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchDrugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchDrugRequest proto.InternalMessageInfo

func (m *SearchDrugRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *SearchDrugRequest) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *SearchDrugRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type SearchDrugResponse struct {
	TotalRow             int32                            `protobuf:"varint,1,opt,name=totalRow,proto3" json:"totalRow,omitempty"`
	List                 []*SearchDrugResponse_DrugDetail `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SearchDrugResponse) Reset()         { *m = SearchDrugResponse{} }
func (m *SearchDrugResponse) String() string { return proto.CompactTextString(m) }
func (*SearchDrugResponse) ProtoMessage()    {}
func (*SearchDrugResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_909770b946af92c6, []int{1}
}

func (m *SearchDrugResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchDrugResponse.Unmarshal(m, b)
}
func (m *SearchDrugResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchDrugResponse.Marshal(b, m, deterministic)
}
func (m *SearchDrugResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchDrugResponse.Merge(m, src)
}
func (m *SearchDrugResponse) XXX_Size() int {
	return xxx_messageInfo_SearchDrugResponse.Size(m)
}
func (m *SearchDrugResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchDrugResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchDrugResponse proto.InternalMessageInfo

func (m *SearchDrugResponse) GetTotalRow() int32 {
	if m != nil {
		return m.TotalRow
	}
	return 0
}

func (m *SearchDrugResponse) GetList() []*SearchDrugResponse_DrugDetail {
	if m != nil {
		return m.List
	}
	return nil
}

type SearchDrugResponse_DrugDetail struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GenericName          string   `protobuf:"bytes,2,opt,name=genericName,proto3" json:"genericName,omitempty"`
	ListImage            string   `protobuf:"bytes,3,opt,name=listImage,proto3" json:"listImage,omitempty"`
	OTCID                int32    `protobuf:"varint,4,opt,name=oTCID,proto3" json:"oTCID,omitempty"`
	Subclass             string   `protobuf:"bytes,5,opt,name=subclass,proto3" json:"subclass,omitempty"`
	DosageForm           string   `protobuf:"bytes,6,opt,name=dosageForm,proto3" json:"dosageForm,omitempty"`
	Specification        string   `protobuf:"bytes,7,opt,name=specification,proto3" json:"specification,omitempty"`
	ManufacturerName     string   `protobuf:"bytes,8,opt,name=manufacturerName,proto3" json:"manufacturerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchDrugResponse_DrugDetail) Reset()         { *m = SearchDrugResponse_DrugDetail{} }
func (m *SearchDrugResponse_DrugDetail) String() string { return proto.CompactTextString(m) }
func (*SearchDrugResponse_DrugDetail) ProtoMessage()    {}
func (*SearchDrugResponse_DrugDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_909770b946af92c6, []int{1, 0}
}

func (m *SearchDrugResponse_DrugDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchDrugResponse_DrugDetail.Unmarshal(m, b)
}
func (m *SearchDrugResponse_DrugDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchDrugResponse_DrugDetail.Marshal(b, m, deterministic)
}
func (m *SearchDrugResponse_DrugDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchDrugResponse_DrugDetail.Merge(m, src)
}
func (m *SearchDrugResponse_DrugDetail) XXX_Size() int {
	return xxx_messageInfo_SearchDrugResponse_DrugDetail.Size(m)
}
func (m *SearchDrugResponse_DrugDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchDrugResponse_DrugDetail.DiscardUnknown(m)
}

var xxx_messageInfo_SearchDrugResponse_DrugDetail proto.InternalMessageInfo

func (m *SearchDrugResponse_DrugDetail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SearchDrugResponse_DrugDetail) GetGenericName() string {
	if m != nil {
		return m.GenericName
	}
	return ""
}

func (m *SearchDrugResponse_DrugDetail) GetListImage() string {
	if m != nil {
		return m.ListImage
	}
	return ""
}

func (m *SearchDrugResponse_DrugDetail) GetOTCID() int32 {
	if m != nil {
		return m.OTCID
	}
	return 0
}

func (m *SearchDrugResponse_DrugDetail) GetSubclass() string {
	if m != nil {
		return m.Subclass
	}
	return ""
}

func (m *SearchDrugResponse_DrugDetail) GetDosageForm() string {
	if m != nil {
		return m.DosageForm
	}
	return ""
}

func (m *SearchDrugResponse_DrugDetail) GetSpecification() string {
	if m != nil {
		return m.Specification
	}
	return ""
}

func (m *SearchDrugResponse_DrugDetail) GetManufacturerName() string {
	if m != nil {
		return m.ManufacturerName
	}
	return ""
}

// 请求参数-根据自己的需求定义
type GetDrugRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDrugRequest) Reset()         { *m = GetDrugRequest{} }
func (m *GetDrugRequest) String() string { return proto.CompactTextString(m) }
func (*GetDrugRequest) ProtoMessage()    {}
func (*GetDrugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_909770b946af92c6, []int{2}
}

func (m *GetDrugRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDrugRequest.Unmarshal(m, b)
}
func (m *GetDrugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDrugRequest.Marshal(b, m, deterministic)
}
func (m *GetDrugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDrugRequest.Merge(m, src)
}
func (m *GetDrugRequest) XXX_Size() int {
	return xxx_messageInfo_GetDrugRequest.Size(m)
}
func (m *GetDrugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDrugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDrugRequest proto.InternalMessageInfo

func (m *GetDrugRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 返回参数-根据自己的需求定义
type GetDrugResponse struct {
	TradeName            string                     `protobuf:"bytes,1,opt,name=tradeName,proto3" json:"tradeName,omitempty"`
	GenericName          string                     `protobuf:"bytes,2,opt,name=genericName,proto3" json:"genericName,omitempty"`
	DetailImage          string                     `protobuf:"bytes,3,opt,name=detailImage,proto3" json:"detailImage,omitempty"`
	Subclass             string                     `protobuf:"bytes,4,opt,name=subclass,proto3" json:"subclass,omitempty"`
	DosageForm           string                     `protobuf:"bytes,5,opt,name=dosageForm,proto3" json:"dosageForm,omitempty"`
	Specification        string                     `protobuf:"bytes,6,opt,name=specification,proto3" json:"specification,omitempty"`
	ApprovalNumber       string                     `protobuf:"bytes,7,opt,name=approvalNumber,proto3" json:"approvalNumber,omitempty"`
	HealthCareLogo       string                     `protobuf:"bytes,8,opt,name=healthCareLogo,proto3" json:"healthCareLogo,omitempty"`
	OTCID                int32                      `protobuf:"varint,9,opt,name=oTCID,proto3" json:"oTCID,omitempty"`
	StorageCondition     string                     `protobuf:"bytes,10,opt,name=storageCondition,proto3" json:"storageCondition,omitempty"`
	ConditionsOfCarriage string                     `protobuf:"bytes,11,opt,name=conditionsOfCarriage,proto3" json:"conditionsOfCarriage,omitempty"`
	ManufacturerName     string                     `protobuf:"bytes,12,opt,name=manufacturerName,proto3" json:"manufacturerName,omitempty"`
	PlaceOfOrigin        string                     `protobuf:"bytes,13,opt,name=placeOfOrigin,proto3" json:"placeOfOrigin,omitempty"`
	Status               GetDrugResponse_DrugStatus `protobuf:"varint,14,opt,name=status,proto3,enum=protobuf.GetDrugResponse_DrugStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetDrugResponse) Reset()         { *m = GetDrugResponse{} }
func (m *GetDrugResponse) String() string { return proto.CompactTextString(m) }
func (*GetDrugResponse) ProtoMessage()    {}
func (*GetDrugResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_909770b946af92c6, []int{3}
}

func (m *GetDrugResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDrugResponse.Unmarshal(m, b)
}
func (m *GetDrugResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDrugResponse.Marshal(b, m, deterministic)
}
func (m *GetDrugResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDrugResponse.Merge(m, src)
}
func (m *GetDrugResponse) XXX_Size() int {
	return xxx_messageInfo_GetDrugResponse.Size(m)
}
func (m *GetDrugResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDrugResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDrugResponse proto.InternalMessageInfo

func (m *GetDrugResponse) GetTradeName() string {
	if m != nil {
		return m.TradeName
	}
	return ""
}

func (m *GetDrugResponse) GetGenericName() string {
	if m != nil {
		return m.GenericName
	}
	return ""
}

func (m *GetDrugResponse) GetDetailImage() string {
	if m != nil {
		return m.DetailImage
	}
	return ""
}

func (m *GetDrugResponse) GetSubclass() string {
	if m != nil {
		return m.Subclass
	}
	return ""
}

func (m *GetDrugResponse) GetDosageForm() string {
	if m != nil {
		return m.DosageForm
	}
	return ""
}

func (m *GetDrugResponse) GetSpecification() string {
	if m != nil {
		return m.Specification
	}
	return ""
}

func (m *GetDrugResponse) GetApprovalNumber() string {
	if m != nil {
		return m.ApprovalNumber
	}
	return ""
}

func (m *GetDrugResponse) GetHealthCareLogo() string {
	if m != nil {
		return m.HealthCareLogo
	}
	return ""
}

func (m *GetDrugResponse) GetOTCID() int32 {
	if m != nil {
		return m.OTCID
	}
	return 0
}

func (m *GetDrugResponse) GetStorageCondition() string {
	if m != nil {
		return m.StorageCondition
	}
	return ""
}

func (m *GetDrugResponse) GetConditionsOfCarriage() string {
	if m != nil {
		return m.ConditionsOfCarriage
	}
	return ""
}

func (m *GetDrugResponse) GetManufacturerName() string {
	if m != nil {
		return m.ManufacturerName
	}
	return ""
}

func (m *GetDrugResponse) GetPlaceOfOrigin() string {
	if m != nil {
		return m.PlaceOfOrigin
	}
	return ""
}

func (m *GetDrugResponse) GetStatus() GetDrugResponse_DrugStatus {
	if m != nil {
		return m.Status
	}
	return GetDrugResponse_NORMAL
}

func init() {
	proto.RegisterEnum("protobuf.GetDrugResponse_DrugStatus", GetDrugResponse_DrugStatus_name, GetDrugResponse_DrugStatus_value)
	proto.RegisterType((*SearchDrugRequest)(nil), "protobuf.SearchDrugRequest")
	proto.RegisterType((*SearchDrugResponse)(nil), "protobuf.SearchDrugResponse")
	proto.RegisterType((*SearchDrugResponse_DrugDetail)(nil), "protobuf.SearchDrugResponse.DrugDetail")
	proto.RegisterType((*GetDrugRequest)(nil), "protobuf.GetDrugRequest")
	proto.RegisterType((*GetDrugResponse)(nil), "protobuf.GetDrugResponse")
}

func init() { proto.RegisterFile("drug.proto", fileDescriptor_909770b946af92c6) }

var fileDescriptor_909770b946af92c6 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x9d, 0xc4, 0x6d, 0x26, 0x34, 0xa4, 0xab, 0x1e, 0x96, 0x52, 0x21, 0xcb, 0xaa, 0x20,
	0x2a, 0x52, 0x0e, 0xe1, 0x08, 0x07, 0x20, 0x51, 0x4b, 0xa4, 0x10, 0x23, 0x87, 0x8a, 0x63, 0xb5,
	0xb1, 0x37, 0xce, 0xaa, 0x8e, 0xd7, 0xec, 0xae, 0xa9, 0xe0, 0xc4, 0x3f, 0xf0, 0x07, 0x7c, 0x15,
	0x9f, 0xc1, 0x27, 0x20, 0xaf, 0x93, 0xd8, 0x49, 0x4d, 0xe1, 0x64, 0xcd, 0xdb, 0x37, 0xb3, 0x33,
	0xef, 0x79, 0x16, 0x20, 0x10, 0x69, 0xd8, 0x4b, 0x04, 0x57, 0x1c, 0x1d, 0xe8, 0xcf, 0x2c, 0x9d,
	0x3b, 0x37, 0x70, 0x34, 0xa5, 0x44, 0xf8, 0x8b, 0xa1, 0x48, 0x43, 0x8f, 0x7e, 0x4e, 0xa9, 0x54,
	0x08, 0xc3, 0xfe, 0x0d, 0xfd, 0x7a, 0xcb, 0x45, 0x80, 0x0d, 0xdb, 0xe8, 0x36, 0xbd, 0x75, 0x88,
	0x6c, 0x68, 0xf9, 0xa9, 0x10, 0x34, 0x56, 0x1f, 0x48, 0x48, 0xb1, 0x69, 0x1b, 0xdd, 0x86, 0x57,
	0x86, 0xd0, 0x09, 0x1c, 0x24, 0x24, 0xa4, 0x53, 0xf6, 0x8d, 0xe2, 0x9a, 0x3e, 0xde, 0xc4, 0xce,
	0x6f, 0x13, 0x50, 0xf9, 0x36, 0x99, 0xf0, 0x58, 0xea, 0x14, 0xc5, 0x15, 0x89, 0x3c, 0x7e, 0xab,
	0xef, 0x6b, 0x78, 0x9b, 0x18, 0xbd, 0x84, 0x7a, 0xc4, 0xa4, 0xc2, 0xa6, 0x5d, 0xeb, 0xb6, 0xfa,
	0xcf, 0x7a, 0xeb, 0xc6, 0x7b, 0x77, 0xeb, 0xf4, 0xb2, 0x60, 0x48, 0x15, 0x61, 0x91, 0xa7, 0x93,
	0x4e, 0xbe, 0x9b, 0x00, 0x05, 0x88, 0xda, 0x60, 0xb2, 0xf5, 0x44, 0x26, 0xd3, 0xc3, 0x84, 0x34,
	0xa6, 0x82, 0xf9, 0x13, 0xb2, 0xcc, 0x87, 0x69, 0x7a, 0x65, 0x08, 0x9d, 0x42, 0x33, 0x2b, 0x34,
	0x5a, 0x66, 0xc3, 0xd6, 0xf4, 0x79, 0x01, 0xa0, 0x63, 0x68, 0xf0, 0x8f, 0x83, 0xd1, 0x10, 0xd7,
	0x75, 0xd3, 0x79, 0x90, 0x4d, 0x23, 0xd3, 0x99, 0x1f, 0x11, 0x29, 0x71, 0x43, 0xa7, 0x6c, 0x62,
	0xf4, 0x04, 0x20, 0xe0, 0x92, 0x84, 0xf4, 0x82, 0x8b, 0x25, 0xb6, 0xf4, 0x69, 0x09, 0x41, 0x67,
	0x70, 0x28, 0x13, 0xea, 0xb3, 0x39, 0xf3, 0x89, 0x62, 0x3c, 0xc6, 0xfb, 0x9a, 0xb2, 0x0d, 0xa2,
	0x73, 0xe8, 0x2c, 0x49, 0x9c, 0xce, 0x89, 0xaf, 0x52, 0x41, 0x85, 0x6e, 0xfe, 0x40, 0x13, 0xef,
	0xe0, 0x8e, 0x0d, 0xed, 0x4b, 0xaa, 0xca, 0xe6, 0xee, 0xa8, 0xe0, 0xfc, 0xaa, 0xc3, 0xc3, 0x0d,
	0x65, 0xe5, 0xc8, 0x29, 0x34, 0x95, 0x20, 0x01, 0xd5, 0xa5, 0x73, 0x6a, 0x01, 0xfc, 0x87, 0x6e,
	0x36, 0xb4, 0x02, 0xad, 0x79, 0x59, 0xb9, 0x32, 0xb4, 0xa5, 0x52, 0xfd, 0x5e, 0x95, 0x1a, 0xff,
	0x56, 0xc9, 0xaa, 0x52, 0xe9, 0x29, 0xb4, 0x49, 0x92, 0x08, 0xfe, 0x85, 0x44, 0x93, 0x74, 0x39,
	0xa3, 0x62, 0x25, 0xe6, 0x0e, 0x9a, 0xf1, 0x16, 0x94, 0x44, 0x6a, 0x31, 0x20, 0x82, 0x8e, 0x79,
	0xc8, 0x57, 0x5a, 0xee, 0xa0, 0x85, 0xdb, 0xcd, 0xb2, 0xdb, 0xe7, 0xd0, 0x91, 0x8a, 0x0b, 0x12,
	0xd2, 0x01, 0x8f, 0x03, 0xa6, 0xdb, 0x81, 0xdc, 0x8b, 0x5d, 0x1c, 0xf5, 0xe1, 0xd8, 0x5f, 0x07,
	0xd2, 0x9d, 0x0f, 0x88, 0x10, 0x2c, 0x93, 0xa7, 0xa5, 0xf9, 0x95, 0x67, 0x95, 0x5e, 0x3f, 0xa8,
	0xf6, 0x3a, 0xd3, 0x25, 0x89, 0x88, 0x4f, 0xdd, 0xb9, 0x2b, 0x58, 0xc8, 0x62, 0x7c, 0x98, 0xeb,
	0xb2, 0x05, 0xa2, 0x57, 0x60, 0x49, 0x45, 0x54, 0x2a, 0x71, 0xdb, 0x36, 0xba, 0xed, 0xfe, 0x59,
	0xb1, 0x53, 0x3b, 0xbf, 0x81, 0x5e, 0xa8, 0xa9, 0xe6, 0x7a, 0xab, 0x1c, 0xe7, 0x79, 0xbe, 0x51,
	0x39, 0x8a, 0x00, 0xac, 0x89, 0xeb, 0xbd, 0x7f, 0x33, 0xee, 0xec, 0xa1, 0x23, 0x38, 0x1c, 0x7a,
	0x57, 0x97, 0xd7, 0x13, 0xf7, 0xfa, 0xc2, 0xbd, 0x9a, 0x0c, 0x3b, 0x46, 0xff, 0x87, 0x01, 0xf5,
	0x8c, 0x8d, 0x5e, 0xc3, 0xfe, 0xaa, 0x36, 0xc2, 0x15, 0xd7, 0xe9, 0x1f, 0xf3, 0xe4, 0xd1, 0x5f,
	0x1b, 0x71, 0xf6, 0xd0, 0x08, 0xa0, 0xd8, 0x78, 0xf4, 0xb8, 0xfa, 0x1d, 0xc8, 0xeb, 0x9c, 0xde,
	0xf7, 0x48, 0x38, 0x7b, 0x6f, 0xad, 0x9f, 0x66, 0xed, 0xdd, 0xf8, 0xd3, 0xcc, 0xd2, 0xb4, 0x17,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x53, 0xe9, 0x5c, 0x76, 0x19, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DrugClient is the client API for Drug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DrugClient interface {
	// Sends a greeting
	GetDrug(ctx context.Context, in *GetDrugRequest, opts ...grpc.CallOption) (*GetDrugResponse, error)
	SearchDrug(ctx context.Context, in *SearchDrugRequest, opts ...grpc.CallOption) (*SearchDrugResponse, error)
}

type drugClient struct {
	cc *grpc.ClientConn
}

func NewDrugClient(cc *grpc.ClientConn) DrugClient {
	return &drugClient{cc}
}

func (c *drugClient) GetDrug(ctx context.Context, in *GetDrugRequest, opts ...grpc.CallOption) (*GetDrugResponse, error) {
	out := new(GetDrugResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Drug/GetDrug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drugClient) SearchDrug(ctx context.Context, in *SearchDrugRequest, opts ...grpc.CallOption) (*SearchDrugResponse, error) {
	out := new(SearchDrugResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Drug/SearchDrug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrugServer is the server API for Drug service.
type DrugServer interface {
	// Sends a greeting
	GetDrug(context.Context, *GetDrugRequest) (*GetDrugResponse, error)
	SearchDrug(context.Context, *SearchDrugRequest) (*SearchDrugResponse, error)
}

// UnimplementedDrugServer can be embedded to have forward compatible implementations.
type UnimplementedDrugServer struct {
}

func (*UnimplementedDrugServer) GetDrug(ctx context.Context, req *GetDrugRequest) (*GetDrugResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDrug not implemented")
}
func (*UnimplementedDrugServer) SearchDrug(ctx context.Context, req *SearchDrugRequest) (*SearchDrugResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDrug not implemented")
}

func RegisterDrugServer(s *grpc.Server, srv DrugServer) {
	s.RegisterService(&_Drug_serviceDesc, srv)
}

func _Drug_GetDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDrugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrugServer).GetDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Drug/GetDrug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrugServer).GetDrug(ctx, req.(*GetDrugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drug_SearchDrug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDrugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrugServer).SearchDrug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Drug/SearchDrug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrugServer).SearchDrug(ctx, req.(*SearchDrugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Drug_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Drug",
	HandlerType: (*DrugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDrug",
			Handler:    _Drug_GetDrug_Handler,
		},
		{
			MethodName: "SearchDrug",
			Handler:    _Drug_SearchDrug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drug.proto",
}
